title: Johann Hagerer
description: Sharing concepts and papers about natural language processing, legal reasoning, and data engineering for students and professionals.
theme: minima

url: "https://jhagerer.github.io"
baseurl: ""
